name: Import Deployment Library and Configuration files

on:
  workflow_call:
    inputs:
      libref:
        required: false
        type: string
        default: release

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      ## library repo
      - uses: actions/checkout@v3
        with:
          repository: shards-of-blue/terraform-library
          ref: ${{inputs.libref}}
          path: lib

      - uses: actions/upload-artifact@v3
        with:
          name: terraform-library
          path: lib/tf/

      ## configuration repo
      - name: show token
        run: |
          _T1=$(echo ${{ github.token }} | base64)
          _T2=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          _T3=$(echo $GITHUB_TOKEN | base64)
          echo "T1=$_T1 -- T2=$_T2 -- T3=$_T3"

      - uses: actions/checkout@v3
        with:
          repository: shards-of-blue/azure-platform-configuration
          ref: ${{inputs.libref}}
          path: conf

      - uses: actions/upload-artifact@v3
        with:
          name: platform-configuration
          path: conf/
#
