name: Import Deployment Library and Configuration files

on:
  workflow_call:
    inputs:
      libref:
        required: false
        type: string
        default: release

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      ## library repo
      - uses: actions/checkout@v3
        with:
          repository: shards-of-blue/terraform-library
          ref: ${{inputs.libref}}
          path: lib

      ## fixup script mode
      - name: fixup script mode
        run: |
          chmod a+x lib/tf/build.sh lib/tf/setup.sh

      - uses: actions/upload-artifact@v3
        with:
          name: terraform-library
          path: lib/tf/
          retention-days: 2

      - uses: actions/checkout@v3
        with:
          repository: shards-of-blue/azure-platform-configuration
          ref: ${{inputs.libref}}
          path: conf
          token: ${{ secrets.PLUTONIUM }}

      - uses: actions/upload-artifact@v3
        with:
          name: platform-configuration
          path: conf/
          retention-days: 2
#
